language: java

git:
  depth: 1

before_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}

script:
  - java -version
  - cd jfuzzylite
  - if [ "$FL_BUILDER" = "mvn" ]; 
    then
    mvn install ;
    fi
  - if [ "$FL_BUILDER" = "ant" ]; 
    then
    ant -f build.xml ;
    fi
    
matrix:
  include:
    - jdk: openjdk13
      env: FL_BUILDER=mvn
    - jdk: openjdk13
      env: FL_BUILDER=ant
      
    - jdk: openjdk12
      env: FL_BUILDER=mvn
    - jdk: openjdk12
      env: FL_BUILDER=ant
      
    - jdk: openjdk11
      env: FL_BUILDER=mvn
    - jdk: openjdk11
      env: FL_BUILDER=ant
      
    - jdk: openjdk10
      env: FL_BUILDER=mvn
    - jdk: openjdk10
      env: FL_BUILDER=ant
      
    - jdk: openjdk9
      env: FL_BUILDER=mvn
    - jdk: openjdk9
      env: FL_BUILDER=ant
      
    - jdk: openjdk8
      env: FL_BUILDER=mvn
    - jdk: openjdk8
      env: FL_BUILDER=ant
      
    - jdk: openjdk7
      env: FL_BUILDER=mvn
    - jdk: openjdk7
      env: FL_BUILDER=ant
      

install:
  - if [[ -n "${MAVEN_VERSION}" ]]; then
        wget https://archive.apache.org/dist/maven/binaries/apache-maven-"${MAVEN_VERSION}"-bin.zip || travis_terminate 1;
        unzip -qq apache-maven-${MAVEN_VERSION}-bin.zip || travis_terminate 1;
        export M2_HOME=$PWD/apache-maven-${MAVEN_VERSION};
        export PATH=$M2_HOME/bin:$PATH;
        mvn -version;
    fi

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: always
    on_failure: always
